### ISSUE TITLE
error while loading shared libraries: libssh.so.4

### ISSUE THREAD

**Issue by fanel545** [matricali/cbrutekrag#17]
After I compile the source and take cbrutekrag and put another vps to start it give me that
![image](https://user-images.githubusercontent.com/36932187/74590414-c9996f80-5016-11ea-9083-b442d1dce594.png)

```
error while loading shared libraries: libssh.so.4: cannot open shared object file
```

**Comment by matricali** [comment]
That's because libssh was linked as a shared library, so the program tries to link the library dynamically at runtime.
The problem is that you don't have libssh in your system.
If you aren't capable to install the library then you can try to make a new build, but linking libssh statically (I wrote a script to do that, take a look at [static-build.sh](static-build.sh))

**Comment by matricali** [comment]
@fanel545 Is this information useful?
Thanks in advance
